import {tmpdir} from 'node:os';import {join} from 'node:path';import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {writeFile} from 'node:fs/promises';
import {createService,validateSubmission} from '../server/service.js';import {fields,visible,clean} from '../shared/proposal.js';import {createProposalPdf} from '../server/pdf.js';import {sendProposalMail} from '../server/mail.js';import handler from '../api/propostas.js';import retry from '../api/reenviar-proposta.js';
const answers={condominio:'Condomínio de teste - NÃO ENVIAR',endereco:'Rua Fictícia, 123',cidade:'Santa Maria / RS',responsavel:'Responsável de teste',telefone:'(55) 99999-1111',email:'teste@example.com',unidades:'20',comerciais:'Não',gas:'Sim',gas_leitor:'Empresa terceirizada',gas_empresa:'Leituras Exemplo Ltda.',necessidade:'Organização, transparência e atendimento.'};
const payload=()=>({answers:{...answers},consent:true,submissionKey:randomUUID(),startedAt:Date.now()-60000,website:''});
function fixture(overrides={}){const rows=new Map();let sends=0,attempts=0;const store={async rate(){return ++attempts<=8},async find(k){return rows.get(k)},async save(row){row={...row,created_at:new Date().toISOString(),condominio:row.answers.condominio,responsavel:row.answers.responsavel,email:row.answers.email,telefone:row.answers.telefone,notification_state:'pending'};if(!rows.has(row.submission_key))rows.set(row.submission_key,row);return rows.get(row.submission_key)},async claim(id){const row=[...rows.values()].find(r=>r.id===id);if(row.notification_state==='sending'||row.notification_state==='sent')return;row.notification_state='sending';return row},async result(id,state){[...rows.values()].find(r=>r.id===id).notification_state=state},...overrides.store};const service=createService({store,makePdf:overrides.makePdf||(()=>Buffer.from('pdf')),sendMail:overrides.sendMail||(()=>{sends++}),rateSecret:'test-secret',...overrides});return{rows,service,sends:()=>sends}}
test('eight stages and gas company condition; discard stale hidden responses',()=>{assert.equal(fields.length,8);const gas=fields.flat().find(f=>f.key==='gas_empresa');assert.ok(visible(gas,answers));assert.ok(!visible(gas,{...answers,gas:'Não'}));assert.equal(clean({...answers,gas:'Não'}).gas_empresa,undefined);assert.equal(clean({...answers,gas_leitor:'Outro'}).gas_empresa,undefined)});
test('server rejects missing consent, invalid quantities, invalid contact and arbitrary options',()=>{assert.throws(()=>validateSubmission({...payload(),consent:false}));for(const change of [{email:'bad'},{unidades:'-1'},{gas_leitor:'injected'},{condominio:42}])assert.throws(()=>validateSubmission({...payload(),answers:{...answers,...change}}))});
test('save before sending; duplicate submission has one record and one email',async()=>{const f=fixture();const p=payload();const first=await f.service.submit(p,'test-ip');const second=await f.service.submit(p,'test-ip');assert.equal(first.protocol,second.protocol);assert.equal(f.rows.size,1);assert.equal(f.sends(),1);assert.equal([...f.rows.values()][0].notification_state,'sent')});
test('failed email retains answers, returns protocol and can be retried',async()=>{let fail=true;const f=fixture({sendMail:()=>{if(fail)throw new Error('provider failure')}});const p=payload(),result=await f.service.submit(p,'test-ip');assert.ok(result.protocol);assert.equal([...f.rows.values()][0].notification_state,'failed');fail=false;await f.service.deliver([...f.rows.values()][0]);assert.equal([...f.rows.values()][0].notification_state,'sent')});
test('missing mail settings retain the saved request',async()=>{const f=fixture({sendMail:()=>{throw Object.assign(new Error(),{code:'MISSING_MAIL'})}});await f.service.submit(payload(),'test-ip');assert.equal([...f.rows.values()][0].notification_state,'configuration_required')});
test('database failure never reports success; submission limit rejects repeated attempts',async()=>{const broken=fixture({store:{async save(){throw new Error('DB unavailable')}}});await assert.rejects(broken.service.submit(payload(),'test-ip'));const f=fixture();for(let i=0;i<8;i++)await f.service.submit(payload(),'test-ip');await assert.rejects(f.service.submit(payload(),'test-ip'),e=>e.status===429)});
test('HTTP endpoint rejects cross-origin and wrong methods; retry is protected',async()=>{const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v},end(v){this.body=v}});let r=res();await handler({method:'GET',headers:{}},r);assert.equal(r.statusCode,405);r=res();await handler({method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'}},r);assert.equal(r.statusCode,403);process.env.ALT_RETRY_TOKEN='x'.repeat(32);r=res();await retry({method:'POST',headers:{authorization:'Bearer wrong'}},r);assert.equal(r.statusCode,403);delete process.env.ALT_RETRY_TOKEN});
test('PDF produces all stages, accented text and long answers without crashing',async()=>{const a={...answers,adicional:'Informações adicionais com acentos: água, gás, síndico. '.repeat(30),necessidade:'Atendimento 👋 e organização.'};const pdf=await createProposalPdf({protocol:'ALT-TESTE',created_at:'2026-10-08T02:20:00Z',answers:a,consent_version:'2026-10-08'});assert.ok(pdf.length>20000);assert.equal(pdf.subarray(0,4).toString(),'%PDF');await writeFile(join(tmpdir(),'ALT-proposta-teste.pdf'),pdf)});
test('email sends PDF as attachment and sets reply-to without calling a real service',async()=>{const previous=globalThis.fetch;let sent;globalThis.fetch=async(url,opts)=>{sent={url,opts,body:JSON.parse(opts.body)};return{ok:true}};try{await sendProposalMail({id:'test',protocol:'ALT-TESTE',condominio:'Condomínio Teste',responsavel:'Teste',telefone:'(55)99999-1111',email:'teste@example.com'},Buffer.from('example-pdf'),{key:'fake-test-key',from:'teste@example.com',to:'destino@example.com'});assert.equal(sent.body.attachments[0].filename,'ALT-proposta-ALT-TESTE.pdf');assert.equal(Buffer.from(sent.body.attachments[0].content,'base64').toString(),'example-pdf');assert.equal(sent.body.reply_to,'teste@example.com')}finally{globalThis.fetch=previous}});
